(PCP-900) Throttle connection resets after crl is expired
puppetlabs/pcp-broker pull request #234
Opened 2020-10-13 21:46 UTC by justinstoller

Previously, in 44ce091, we began closing all connections after a CRL
update to prevent stale SSLContexts from being held in memory. However,
the previous change dropped all connections in quick succession and
there was some concern that it could cause undo spikes in load from a
thundering herd of reconnection attempts.

This patch creates a background thread (the same as how we send inventory
updates) that every X milliseconds tries to close any Connections in the
inventory marked expired. It also throttles the attempt to close all
connections by sleeping Y milliseconds between each Connection it
closes. X and Y are configurable by the new config values
`crl-check-period` and `expired-conn-throttle` respectively. The default
to 60 seconds between CRL checks and 60 milliseconds between individual
Connection closes.

This should give a small but meaningful window for multiple CRL updates
to coalesce and cause connection resets for a 1000-connections-per-broker
deployment to take around 1 minute. Note, the `crl-check-period` is waited
for after/in-additon-to whatever time it takes to close any existing
expired connections.

Previously, the file-system watcher which used to trigger the connection
closing on CRL update now only marks existing Connections as expired for
the background thread to purge in its configured time.

2020-10-13 21:48 UTC, justinstoller commented
This provides the spacing out of connection resets that @MikaelSmith encouraged in this [comment](https://github.com/puppetlabs/pcp-broker/pull/228#issuecomment-657734862).

2020-10-13 21:54 UTC, justinstoller commented
Gah, I forgot that schema validation only happens when running with a special profile, fixing.

2020-10-13 21:57 UTC, justinstoller commented
fwiw, I looked into one significantly different approach and one other implementation of this approach.

A different approach I researched was creating a custom onPong event handler to close an expired connection when it did it's ping-pong interaction. However Jetty _really_ doesn't want users writing custom onPong handlers and doing so looked like it might require reworking both pcp-broker and tk-jetty9.

A different implementation could have used tk-scheduler, however since we were already doing something very similar with a `future` for inventory updates, I went with this implementation.

2020-10-13 22:12 UTC, justinstoller commented
Fixed the schema testing, I'd love a quick look from someone on this.

2020-10-13 22:18 UTC, justinstoller commented
Also, if folks want to look at the logs the primary/console is "grey-expression" and I have six agents connected to the compiler "diehard-frog" (all in the pooler).

2020-10-14 11:00 UTC, puppetcla commented
CLA signed by all contributors.

2020-10-14 17:09 UTC, McdonaldSeanp approved these changes

2020-10-14 19:21 UTC, MikaelSmith requested changes
Approach looks good. Pointed out a few things to fix.

2020-10-14 19:21 UTC, MikaelSmith commented on src/puppetlabs/pcp/broker/core.clj
> +               #(i18n/trs "Checking the existing {0} connections for expired CRLs."))
I don't think this log invocation is right, it needs to pass an argument for `{0}` to `i18n/trs` as done at line 706.

2020-10-14 19:21 UTC, MikaelSmith commented on src/puppetlabs/pcp/broker/service.clj
> +              expired-conn-throttle (get-in-config [:pcp-broker :expired-conn-throttle] 30)
Is this 30ms? That doesn't seem to match the commit message.

2020-10-14 19:21 UTC, MikaelSmith commented on src/puppetlabs/pcp/broker/service.clj
> +              expired-conn-throttle (get-in-config [:pcp-broker :expired-conn-throttle] 30)
We should update https://github.com/puppetlabs/pcp-broker/blob/master/doc/configuration.md with these new config options.

2020-10-14 19:21 UTC, MikaelSmith commented on test/unit/puppetlabs/pcp/broker/core_test.clj
> +(deftest expire-connection-test
A test that expired connections are removed from the inventory would be handy.

2020-10-14 20:23 UTC, justinstoller commented on src/puppetlabs/pcp/broker/service.clj
> +              expired-conn-throttle (get-in-config [:pcp-broker :expired-conn-throttle] 30)
Sorry, I noticed that and went back and updated the commit message, but forgot to update the GH PR description.

2020-10-14 20:34 UTC, justinstoller commented on src/puppetlabs/pcp/broker/service.clj
> +              expired-conn-throttle (get-in-config [:pcp-broker :expired-conn-throttle] 30)
Thanks for calling out the docs updates, missed those for the idle-timeout work as well.

2020-10-14 22:12 UTC, justinstoller commented on test/unit/puppetlabs/pcp/broker/core_test.clj
> +(deftest expire-connection-test
I'm adding a test to show that they have `websockets/close!` called on them. Do you think that's sufficient, or should I validate that closing a connection does eventually trigger an inventory update?

2020-10-14 22:29 UTC, MikaelSmith commented on test/unit/puppetlabs/pcp/broker/core_test.clj
> +(deftest expire-connection-test
That's enough for me.

2020-10-14 22:50 UTC, justinstoller commented
Thanks for the review, I think I've addressed the feedback.

2020-10-14 22:55 UTC, MikaelSmith commented on test/unit/puppetlabs/pcp/broker/core_test.clj
> +          (close-expired-connections! broker)
Could this have a timing component? The close will happen up to 10ms after `expire-ssl-connections`.

2020-10-14 23:00 UTC, justinstoller commented on test/unit/puppetlabs/pcp/broker/core_test.clj
> +          (close-expired-connections! broker)
Like increasing the throttle time and validating that it is honored?

2020-10-14 23:00 UTC, MikaelSmith commented on test/unit/puppetlabs/pcp/broker/core_test.clj
> +          (close-expired-connections! broker)
I was thinking more that the test might fail, unless I'm forgetting how `realized?` works.

2020-10-14 23:01 UTC, justinstoller commented on test/unit/puppetlabs/pcp/broker/core_test.clj
> +          (close-expired-connections! broker)
Or waiting on the promise with a timeout to ensure this doesn't get racey?

2020-10-14 23:01 UTC, justinstoller commented on test/unit/puppetlabs/pcp/broker/core_test.clj
> +          (close-expired-connections! broker)
I should probably just do both  ( ;

2020-10-15 00:07 UTC, justinstoller commented on test/unit/puppetlabs/pcp/broker/core_test.clj
> +          (close-expired-connections! broker)
Updated to check both sides of the wait, let me know if I missed something.

2020-10-15 00:14 UTC, MikaelSmith approved these changes

2020-10-15 01:15 UTC, merged